export const REMINDER_REPOSITORY = Symbol('REMINDER_REPOSITORY');
export const CREATE_REMINDER_USE_CASE = Symbol('CREATE_REMINDER_USE_CASE');
export const GET_REMINDERS_USE_CASE = Symbol('GET_REMINDERS_USE_CASE');
export const UPDATE_REMINDER_USE_CASE = Symbol('UPDATE_REMINDER_USE_CASE');
export const DELETE_REMINDER_USE_CASE = Symbol('DELETE_REMINDER_USE_CASE');

